skip-check:
  - CKV_AZURE_7
  - CKV_AZURE_4
  - CKV_AZURE_171
  - CKV_AZURE_6
  - CKV_AZURE_168
  - CKV_AZURE_141
  - CKV_AZURE_117
  - CKV_AZURE_116
  - CKV_AZURE_172
  - CKV_AZURE_115
  - CKV_AZURE_227
  - CKV_AZURE_170
  - CKV_AZURE_226
  - CKV_AZURE_232
  - CKV_AZURE_50
  - CKV_AZURE_119
  - CKV2_AZURE_31
  - CKV_AZURE_10